{% set name = "pdpyras" %}
{% set version = "5.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdpyras-{{ version }}.tar.gz
  sha256: 515c8a34b8f52ad38878c9df25d07ccb809de010d2b85b56d42858c03e7c1fcb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - requests
    - urllib3

test:
  imports:
    - pdpyras
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pagerduty.github.io/pdpyras
  summary: PagerDuty REST API client
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/PagerDuty/pdpyras
  doc_url: https://pagerduty.github.io/pdpyras

extra:
  recipe-maintainers:
    - xylar
